GlobalPlanner:

  allow_unknown: true
  default_tolerance: 0.1

  use_dijkstra: false
  use_quadratic: false
  use_grid_path: true

  lethal_cost: 253
  neutral_cost: 50
  cost_factor: 3

  visualize_potential: false
  #orientation_window_size: 2
  orientation_mode: 0
