local_costmap:
  global_frame: odom
  robot_base_frame: chassis
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05


  obstacle_layer:
    enabled: true
    obstacle_range: 3.0
    raytrace_range: 4.0
    inflation_radius: 0.2
    track_unknown_space: true
    combination_method: 1

    observation_sources: laser_scan_sensor
    laser_scan_sensor: {data_type: LaserScan, topic: /slammer/laser/scan, marking: true, clearing: true}

  inflation_layer:
    enabled:              true
    cost_scaling_factor:  30.0
    inflation_radius:     0.3