TebLocalPlannerROS:


 odom_topic: odom



 max_vel_x: 0.5 #1.0572
 max_vel_x_backwards: 0.03
 max_vel_theta: 16.0 #10.2
 acc_lim_x: 0.2
 acc_lim_theta: 0.5 #5.0
 min_turning_radius: 0.0
 footprint_model:
  type: "polygon"
  vertices: [ [-0.06, -0.194], [-0.06, 0.194], [0.06, 0.194], [0.06, -0.194] ]


 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.2
 free_goal_vel: False

 min_samples: 3
 max_samples: 500
 max_global_plan_lookahead_dist: 3.0
 force_reinit_new_goal_dist: 0.5
 feasibility_check_no_poses: 5.0
 allow_init_with_backwards_motion: True
 exact_arc_length: False
 shrink_horizon_min_duration: 10
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True


 min_obstacle_dist: 0.2
 costmap_obstacles_behind_robot_dist: 3.0
 inflation_dist: 0.05
 obstacle_association_cutoff_factor: 5.0
 obstacle_association_force_inclusion_factor: 2.0
 obstacle_poses_affected: 10
 include_costmap_obstacles: True


 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 2 #5




 no_inner_iterations: 3
 no_outer_iterations: 3
 penalty_epsilon: 0.01




 optimization_activate: True
 optimization_verbose: False


 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 5
 weight_kinematics_nh: 10000
 weight_kinematics_forward_drive: 900

 weight_optimaltime: 2
 weight_obstacle: 800
 weight_viapoint: 10
 weight_inflation: 0.1
 weight_adapt_factor: 2
 weight_shortest_path: 2




 enable_homotopy_class_planning: True
 enable_multithreading: True


 max_number_classes: 5
 selection_cost_hysteresis: 1.6
 selection_obst_cost_scale: 100
 selection_viapoint_cost_scale: 1
 global_plan_viapoint_sep: 1

 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 8


 h_signature_prescaler: 1


 obstacle_heading_threshold: 0.45


 shrink_horizon_backup: True
 oscillation_recovery: True
 oscillation_v_eps: 0.1
 oscillation_omega_eps: 0.1
 oscillation_recovery_min_duration: 10
 oscillation_filter_duration: 10
